Repository grafana/plugin-validator, pull requests merged in 2024-05, with the labels that each got.

#191 Update README to check go version in go.mod file
  README.md
Labels: documentation

#173 chore: update packages and images
  .github/workflows/release.yml
  .github/workflows/test.yml
  Dockerfile
  go.mod
  go.sum
Labels: dependencies, github_actions

#196 Meta-data schema validator: Use the current plugin.json schema
  pkg/analysis/passes/metadataschema/metadataschema.go
Labels: bug

#201 Add LLMValidate and remove tzap gpt
  Magefile.go
  go.mod
  go.sum
  pkg/analysis/passes/analysis.go
  pkg/analysis/passes/llmreview/llmreview.go
  pkg/analysis/passes/tzap-gpt/tzap-gpt.go
  pkg/analysis/passes/tzap-gpt/tzapignore.txt
  pkg/analysis/passes/tzap-gpt/tzapinclude.txt
  pkg/cmd/plugincheck2/main_test.go
  pkg/llmvalidate/llmvalidate.go
Labels: enhancement
